# fly.toml app configuration file generated for js-nginx-auth on 2023-07-15T09:00:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "${FLY_APP_NAME}"
primary_region = "${FLY_PRIMARY_REGION}"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
